version: v2
name: js-test-app-dockerfile
services:
- name: web
  run: node index.js
  type: web
build:
  context: ./
  method: docker
  dockerfile: ./docker/Dockerfile
version: v2
predeploy:
  run: ls
