"on":
  push:
    branches:
    - dgtown
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Deploy stack
      timeout-minutes: 30
      uses: porter-dev/porter-cli-action@v0.1.0
      with:
        command: apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: "2814"
        PORTER_HOST: https://dashboard-production.porter.run
        PORTER_PROJECT: "7694"
        PORTER_STACK_NAME: dgt
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_7694_2814 }}
