on:
  push:
    branches:
    - feroze
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Deploy stack
      timeout-minutes: 30
      uses: porter-dev/porter-cli-action@dev
      with:
        command: apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: "11"
        PORTER_HOST: https://dashboard.internal-tools.porter.run
        PORTER_PROJECT: 8
        PORTER_STACK_NAME: feroze-will-delete-this
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_8_11 }}
