on:
  push:
    branches:
    - feroze
name: Deploy to porter_stack_pls-work-1
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Install Porter
      timeout-minutes: 30
      run: /bin/bash -c "$(curl -fsSL https://install.porter.run)"
    - name: Deploy stack
      timeout-minutes: 30
      run: porter apply
      env:
        PORTER_CLUSTER: 2698
        PORTER_HOST: https://dashboard.getporter.dev
        PORTER_PROJECT: 7224
        PORTER_STACK_NAME: pls-work-1
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_7_11 }}
